//square
//moment
export const UP_MOMENT = 'UP_MOMENT';
export const DOWN_MOMENT = 'DOWN_MOMENT';
export const INIT_FOCUSED_MOMENTS = 'INIT_FOCUSED_MOMENTS';
export const INIT_HOT_MOMENTS = 'INIT_HOT_MOMENTS';
export const INIT_RECOMMAND_MOMENTS = 'INIT_RECOMMAND_MOMENTS';
export const INIT_COLLECTED_MOMENTS = 'INIT_COLLECTED_MOMENTS';
export const INIT_MOMENTS = 'INIT_MOMENTS';
export const ADD_MOMENTS = 'ADD_MOMENTS';

export const DELETE_COLLECTED_MOMENTS = 'DELETE_COLLECTED_MOMENTS';
export const INIT_USER_CENTER_MOMENTS = 'INIT_USER_CENTER_MOMENTS';

export const PROVIDER_COLLECT_MOMENT = 'PROVIDER_COLLECT_MOMENT';
export const PROVIDER_CANCEL_COLLECT_MOMENT = 'PROVIDER_CANCEL_COLLECT_MOMENT';
export const PROVIDER_HIDE_MOMENT = 'PROVIDER_HIDE_MOMENT';
export const PROVIDER_UP_MOMENT = 'PROVIDER_UP_MOMENT';
export const PROVIDER_CANCEL_UP_MOMENT = 'PROVIDER_CANCEL_UP_MOMENT';
export const PROVIDER_DELETE_MOMENT = 'PROVIDER_DELETE_MOMENT';
export const PROVIDER_INCREASE_COMMENT = 'PROVIDER_INCREASE_COMMENT';
export const PROVIDER_DECREASE_COMMENT = 'PROVIDER_DECREASE_COMMENT';

//focused users
export const SET_FOCUSED_USERS = 'SET_FOCUSED_USERS';
export const ADD_FOCUSED_USERS = 'ADD_FOCUSED_USERS';
export const DELETE_FOCUSED_USERS = 'DELETE_FOCUSED_USERS';
export const SET_FOCUSED_USERS_PAGE = 'SET_FOCUSED_USERS_PAGE';

//fans
export const SET_FANS = 'SET_FANS';
export const SET_FANS_PAGE = 'SET_FANS_PAGE';

//SDK
// session-tab
export const SET_SESSION = 'SET_SESSION';
export const SET_CURRENT_SESSION_ID = 'SET_CURRENT_SESSION_ID';
//friend-tab
export const SET_TAB_ID_FRIEND = 'SET_TAB_ID_FRIEND';
//team-tab
export const SET_TAB_ID_TEAM = 'SET_TAB_ID_TEAM';
//teamMembers
export const SET_TEAM_MEMBERS = 'SET_TEAM_MEMBERS';
//team
export const SET_TEAM_MAP = 'SET_TEAM_MAP';
export const UPDATE_TEAM = 'UPDATE_TEAM';
//friend
export const SET_FRIEND_LIST = 'SET_FRIEND_LIST';
export const UPDATE_FRIEND_ALIAS = 'UPDATE_FRIEND_ALIAS';
//user
export const SET_PERSON_LIST = 'SET_PERSON_LIST';
export const UPDATE_PERSON_LIST = 'UPDATE_PERSON_LIST';
//black list
export const SET_BLACK_LIST = 'SET_BLACK_LIST';
//msg
export const ADD_MSG = 'ADD_MSG';
export const ADD_MSGS = 'ADD_MSGS';
export const SET_MSG = 'SET_MSG';
export const BACKOUT_MSG = 'BACKOUT_MSG';
//history msg
export const ADD_HISTORY_MSG_BY_REVERSE = 'ADD_HISTORY_MSG_BY_REVERSE';
export const SET_HISTORY_MSG = 'SET_HISTORY_MSG';
//userUID
export const SET_USER_UID = 'SET_USER_UID';
//token
export const SET_SERVER_TOKEN = "SET_SERVER_TOKEN";
//aesKet
export const SET_AES_KEY = 'SET_AES_KEY';
//serverConfig
export const SET_SERVER_CONFIG = 'SET_SERVER_CONFIG';
export const SET_IMAGE_ROOT = 'SET_IMAGE_ROOT';
//mtsdk
export const SET_MTSDK = 'SET_MTSDK';

//switchs
export const TOGGLE_SOUND_NOTE_SWITCH = 'TOGGLE_SOUND_NOTE_SWITCH';
export const TOGGLE_DESKTOP_NOTE_SWITCH = 'TOGGLE_DESKTOP_NOTE_SWITCH';
//hide memberlist
export const OFF_MEMBER_LIST_SWITCH = 'OFF_MEMBER_LIST_SWITCH';
//TOGGLE memberlist
export const TOGGLE_MEMBER_LIST_SWITCH = 'TOGGLE_MEMBER_LIST_SWITCH';
//session menu
export const TOGGLE_SESSION_MENU_SWITCH = 'TOGGLE_SESSION_MENU_SWITCH';
export const OFF_SESSION_MENU_SWITCH = 'OFF_SESSION_MENU_SWITCH';
//chatting history
export const SHOW_CHATTING_HISTORY = 'SHOW_CHATTING_HISTORY';
export const HIDE_CHATTING_HISTORY = 'HIDE_CHATTING_HISTORY';

//search words
export const SET_SEARCH_WORDS = 'SET_SEARCH_WORDS';
//search result
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';

//friendshipApplies
export const ADD_FRIENDSHIP_APPLY = 'ADD_FRIENDSHIP_APPLY';
export const ALLOW_FRIENDSHIP_APPLY = 'ALLOW_FRIENDSHIP_APPLY';

//moment follower
export const FOCUS_USER_IN_MOMENT = 'FOCUS_USER_IN_MOMENT';
export const CANCEL_FOCUS_USER_IN_MOMENT = 'CANCEL_FOCUS_USER_IN_MOMENT';

//sysNotification
export const ADD_SYS_NOTIFICATION = 'ADD_SYS_NOTIFICATION';
export const CLEAN_SYS_NOTIFICATION = 'CLEAN_SYS_NOTIFICATION';